"""Droped Enum, as a replacement Enum, was created Enum Status Table

Revision ID: 847d4b974cf8
Revises: c3e91a7b4d12
Create Date: 2026-09-22 17:11:43.940178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '847d4b974cf8'
down_revision: Union[str, Sequence[str], None] = 'c3e91a7b4d12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enum_status',
    sa.Column('id', sa.SmallInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('data', sa.VARCHAR(length=14), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enum_status'))
    )
    op.execute("INSERT INTO enum_status (data) VALUES ('CREATED')")

    op.add_column('order', sa.Column('status_id', sa.SmallInteger(), nullable=True))

    op.execute("UPDATE \"order\" SET status_id = 1")

    op.alter_column('order', 'status_id', nullable=False)

    op.create_foreign_key(op.f('fk_order_status_id_enum_status'), 'order', 'enum_status', ['status_id'], ['id'])
    op.drop_column('order', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('status', postgresql.ENUM('created', 'processing', 'paid', 'failure', name='orderstatus'), server_default=sa.text("'created'::orderstatus"), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_order_status_id_enum_status'), 'order', type_='foreignkey')
    op.drop_column('order', 'status_id')
    op.drop_table('enum_status')
    # ### end Alembic commands ###
