"""added status to order and quantity to order_content

Revision ID: b8c702ba686d
Revises: d50c0f8802a9
Create Date: 2026-09-08 21:52:09.443602

"""
from typing import Sequence, Union
from sqlalchemy.dialects import postgresql

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8c702ba686d'
down_revision: Union[str, Sequence[str], None] = 'd50c0f8802a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    order_status_enum = postgresql.ENUM('PENDING', 'PAID', 'SHIPPED', 'CANCELLED', name='orderstatus')
    order_status_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('status', order_status_enum, server_default='PENDING', nullable=False))
    op.add_column('order_content', sa.Column('quantity', sa.Integer(), server_default='1', nullable=False))
    op.drop_constraint(op.f('promo_promo_key'), 'promo', type_='unique')
    op.create_index(op.f('ix_promo_id'), 'promo', ['id'], unique=False)
    op.create_unique_constraint(op.f('uq_promo_promo'), 'promo', ['promo'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_promo_promo'), 'promo', type_='unique')
    op.drop_index(op.f('ix_promo_id'), table_name='promo')
    op.create_unique_constraint(op.f('promo_promo_key'), 'promo', ['promo'], postgresql_nulls_not_distinct=False)
    op.drop_column('order_content', 'quantity')
    op.drop_column('order', 'status')
    # ### end Alembic commands ###

    order_status_enum = postgresql.ENUM('PENDING', 'PAID', 'SHIPPED', 'CANCELLED', name='orderstatus')
    order_status_enum.drop(op.get_bind(), checkfirst=True)