"""Initial tables

Revision ID: d50c0f8802a9
Revises: 
Create Date: 2026-08-30 15:20:12.883959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd50c0f8802a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_cart_id'), 'cart', ['id'], unique=False)
    op.alter_column('clothing', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.DECIMAL(precision=10, scale=2),
               nullable=False)
    op.create_index(op.f('ix_clothing_id'), 'clothing', ['id'], unique=False)
    op.create_index(op.f('ix_favorite_id'), 'favorite', ['id'], unique=False)
    op.drop_constraint(op.f('fk_favorite_clothing'), 'favorite', type_='foreignkey')
    op.drop_constraint(op.f('fk_favorite_user'), 'favorite', type_='foreignkey')
    op.create_foreign_key(None, 'favorite', 'clothing', ['id_clothing'], ['id'])
    op.create_foreign_key(None, 'favorite', 'user', ['id_user'], ['id'])
    op.add_column('order', sa.Column('price', sa.DECIMAL(precision=10, scale=2), server_default='0', nullable=False))
    op.alter_column('order', 'postal_number',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('order', 'date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_order_id'), 'order', ['id'], unique=False)
    op.drop_column('order', 'cost')
    op.create_index(op.f('ix_order_content_id'), 'order_content', ['id'], unique=False)
    op.drop_constraint(op.f('fk_order_content_order'), 'order_content', type_='foreignkey')
    op.drop_constraint(op.f('fk_order_content_clothing'), 'order_content', type_='foreignkey')
    op.create_foreign_key(None, 'order_content', 'order', ['id_order'], ['id'])
    op.create_foreign_key(None, 'order_content', 'clothing', ['id_clothing'], ['id'])
    op.alter_column('user', 'phone_number',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.alter_column('user', 'phone_number',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'order_content', type_='foreignkey')
    op.drop_constraint(None, 'order_content', type_='foreignkey')
    op.create_foreign_key(op.f('fk_order_content_clothing'), 'order_content', 'clothing', ['id_clothing'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_order_content_order'), 'order_content', 'order', ['id_order'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_order_content_id'), table_name='order_content')
    op.add_column('order', sa.Column('cost', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_order_id'), table_name='order')
    op.alter_column('order', 'date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('order', 'postal_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('order', 'price')
    op.drop_constraint(None, 'favorite', type_='foreignkey')
    op.drop_constraint(None, 'favorite', type_='foreignkey')
    op.create_foreign_key(op.f('fk_favorite_user'), 'favorite', 'user', ['id_user'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_favorite_clothing'), 'favorite', 'clothing', ['id_clothing'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_favorite_id'), table_name='favorite')
    op.drop_index(op.f('ix_clothing_id'), table_name='clothing')
    op.alter_column('clothing', 'price',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_index(op.f('ix_cart_id'), table_name='cart')
    # ### end Alembic commands ###
